cask 'alfred'
cask 'bettertouchtool'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'kaleidoscope'
cask 'pastebot'
cask 'slack'
cask 'visual-studio-code'

brew 'fzf'
brew 'gh'
brew 'graphviz'
brew 'ripgrep'
brew 'rcm'
brew 'shellcheck'
