#!/bin/bash

setup/echo-banner "Pulling private preferences"

if ! which gh >/dev/null; then
  echo "gh is not installed. Please make sure brew bundle completed successfully"
  exit 1
fi

if [ ! -d ../private-mac-preferences ]; then
  gh repo clone sethfri/private-mac-preferences ../private-mac-preferences
else
  echo "Private preferences already downloaded"
fi
